/**
 * Minimal, self-contained ISO 3166-1 alpha-2 lookup.
 *
 * Vendored deliberately so the MCP server has zero dependency on the
 * EasyOnward frontend/backend code. Covers the official short names plus a
 * handful of common aliases. This does NOT need to be exhaustive — the
 * visa-pair API is the source of truth for which pairs are catalogued; this
 * map only exists to let the model pass a country *name* and have us resolve
 * it to the ISO-2 code the API expects.
 */

const NAME_TO_ALPHA2: Record<string, string> = {
  afghanistan: "AF",
  "aland islands": "AX",
  albania: "AL",
  algeria: "DZ",
  "american samoa": "AS",
  andorra: "AD",
  angola: "AO",
  anguilla: "AI",
  antarctica: "AQ",
  "antigua and barbuda": "AG",
  antigua: "AG",
  argentina: "AR",
  armenia: "AM",
  aruba: "AW",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  "the bahamas": "BS",
  bahrain: "BH",
  bangladesh: "BD",
  barbados: "BB",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  benin: "BJ",
  bermuda: "BM",
  bhutan: "BT",
  bolivia: "BO",
  "bonaire, sint eustatius and saba": "BQ",
  "bosnia and herzegovina": "BA",
  bosnia: "BA",
  botswana: "BW",
  "bouvet island": "BV",
  brazil: "BR",
  "british indian ocean territory": "IO",
  "brunei darussalam": "BN",
  brunei: "BN",
  bulgaria: "BG",
  "burkina faso": "BF",
  burundi: "BI",
  "cabo verde": "CV",
  "cape verde": "CV",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  "cayman islands": "KY",
  "central african republic": "CF",
  chad: "TD",
  chile: "CL",
  china: "CN",
  "christmas island": "CX",
  "cocos islands": "CC",
  "cocos (keeling) islands": "CC",
  colombia: "CO",
  comoros: "KM",
  congo: "CG",
  "republic of the congo": "CG",
  "congo, the democratic republic of the": "CD",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  "ivory coast": "CI",
  croatia: "HR",
  cuba: "CU",
  curacao: "CW",
  cyprus: "CY",
  czechia: "CZ",
  "czech republic": "CZ",
  denmark: "DK",
  djibouti: "DJ",
  dominica: "DM",
  "dominican republic": "DO",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  estonia: "EE",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  "falkland islands": "FK",
  "faroe islands": "FO",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  gabon: "GA",
  gambia: "GM",
  "the gambia": "GM",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  gibraltar: "GI",
  greece: "GR",
  greenland: "GL",
  grenada: "GD",
  guadeloupe: "GP",
  guam: "GU",
  guatemala: "GT",
  guernsey: "GG",
  guinea: "GN",
  "guinea-bissau": "GW",
  guyana: "GY",
  haiti: "HT",
  "heard island and mcdonald islands": "HM",
  "holy see": "VA",
  "vatican city": "VA",
  vatican: "VA",
  honduras: "HN",
  "hong kong": "HK",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  "isle of man": "IM",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  jersey: "JE",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kiribati: "KI",
  "north korea": "KP",
  "korea, democratic people's republic of": "KP",
  "south korea": "KR",
  "korea, republic of": "KR",
  korea: "KR",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  "lao people's democratic republic": "LA",
  latvia: "LV",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  macao: "MO",
  macau: "MO",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  "marshall islands": "MH",
  martinique: "MQ",
  mauritania: "MR",
  mauritius: "MU",
  mayotte: "YT",
  mexico: "MX",
  micronesia: "FM",
  moldova: "MD",
  monaco: "MC",
  mongolia: "MN",
  montenegro: "ME",
  montserrat: "MS",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  burma: "MM",
  namibia: "NA",
  nauru: "NR",
  nepal: "NP",
  netherlands: "NL",
  "the netherlands": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  niue: "NU",
  "norfolk island": "NF",
  "north macedonia": "MK",
  macedonia: "MK",
  "northern mariana islands": "MP",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  palau: "PW",
  palestine: "PS",
  "palestine, state of": "PS",
  panama: "PA",
  "papua new guinea": "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  "the philippines": "PH",
  pitcairn: "PN",
  poland: "PL",
  portugal: "PT",
  "puerto rico": "PR",
  qatar: "QA",
  reunion: "RE",
  romania: "RO",
  russia: "RU",
  "russian federation": "RU",
  rwanda: "RW",
  "saint barthelemy": "BL",
  "saint helena": "SH",
  "saint kitts and nevis": "KN",
  "st kitts and nevis": "KN",
  "st. kitts and nevis": "KN",
  "saint lucia": "LC",
  "st lucia": "LC",
  "saint martin": "MF",
  "saint pierre and miquelon": "PM",
  "saint vincent and the grenadines": "VC",
  "st vincent and the grenadines": "VC",
  samoa: "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "saudi arabia": "SA",
  senegal: "SN",
  serbia: "RS",
  seychelles: "SC",
  "sierra leone": "SL",
  singapore: "SG",
  "sint maarten": "SX",
  slovakia: "SK",
  slovenia: "SI",
  "solomon islands": "SB",
  somalia: "SO",
  "south africa": "ZA",
  "south georgia and the south sandwich islands": "GS",
  "south sudan": "SS",
  spain: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  suriname: "SR",
  "svalbard and jan mayen": "SJ",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  "syrian arab republic": "SY",
  taiwan: "TW",
  tajikistan: "TJ",
  tanzania: "TZ",
  thailand: "TH",
  "timor-leste": "TL",
  "east timor": "TL",
  togo: "TG",
  tokelau: "TK",
  tonga: "TO",
  "trinidad and tobago": "TT",
  trinidad: "TT",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  turkmenistan: "TM",
  "turks and caicos islands": "TC",
  "turks and caicos": "TC",
  tuvalu: "TV",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  britain: "GB",
  england: "GB",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  "u.s.a.": "US",
  "u.s.": "US",
  america: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  venezuela: "VE",
  vietnam: "VN",
  "viet nam": "VN",
  "british virgin islands": "VG",
  "virgin islands, british": "VG",
  "us virgin islands": "VI",
  "virgin islands, u.s.": "VI",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
};

// Set of all valid alpha-2 codes (derived from the values above).
const ALPHA2_CODES = new Set(Object.values(NAME_TO_ALPHA2));

function normalize(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/^the\s+/, "the "); // keep "the " prefix as-is for keyed lookups
}

/**
 * Resolve a user-supplied country reference (ISO-2 code or common name)
 * to an uppercase ISO 3166-1 alpha-2 code. Returns null if unresolvable.
 */
export function resolveCountry(input: string): string | null {
  if (!input) return null;
  const raw = input.trim();

  // Direct alpha-2 code (case-insensitive). Only short-circuit on codes we
  // recognise — otherwise fall through to the name map, so common 2-letter
  // aliases that are NOT valid ISO codes (e.g. "UK" → GB) resolve correctly.
  if (/^[A-Za-z]{2}$/.test(raw)) {
    const code = raw.toUpperCase();
    if (ALPHA2_CODES.has(code)) return code;
    const aliased = NAME_TO_ALPHA2[raw.toLowerCase()];
    if (aliased) return aliased;
    // Accept any other well-formed 2-letter code as-is — the API will 404 if
    // it's not catalogued, which we handle gracefully.
    return code;
  }

  const key = normalize(raw);
  if (NAME_TO_ALPHA2[key]) return NAME_TO_ALPHA2[key];

  // Try without a leading "the ".
  const noThe = key.replace(/^the\s+/, "");
  if (NAME_TO_ALPHA2[noThe]) return NAME_TO_ALPHA2[noThe];

  return null;
}

export function isKnownAlpha2(code: string): boolean {
  return ALPHA2_CODES.has(code.toUpperCase());
}
